In [1]:
##### 1. Import the numpy package under the name `np` (★☆☆)

import numpy as np

In [3]:
 #2. Create a null vector of size 10 (★☆☆)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
 #4. Create a vector with values ranging from 10 to 49 (★☆☆)
x = np.arange(10,50)
print(x)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
# 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
#6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#`hint: np.nonzero
x=[1,2,0,0,4,0]
print(np.nonzero(x))


(array([0, 1, 4]),)


In [16]:
7.#Create a 3x3 identity matrix (★☆☆)`hint: np.eye`
x = np.eye(3)
print(x)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# 8. Create a 3x3x3 array with random values (★☆☆)`hint: np.random.random`
x = np.random.random((3,3,3))
print(x)



[[[0.26288777 0.7402768  0.41290296]
  [0.09534717 0.90243628 0.5825173 ]
  [0.77434507 0.18660283 0.02761694]]

 [[0.84816352 0.24817859 0.64112226]
  [0.41692002 0.3245956  0.57769528]
  [0.88806019 0.26271656 0.7602296 ]]

 [[0.44381149 0.49523886 0.1507783 ]
  [0.83424324 0.27234385 0.49616571]
  [0.66618597 0.92051479 0.96790993]]]


In [19]:
# 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)min, max`
x = np.random.random(10)
print(x)

[0.82476471 0.10333376 0.92038457 0.55949987 0.33987561 0.60611587
 0.21869797 0.63568401 0.41320965 0.76043841]


In [28]:
#10Create a random vector of size 30 and find the mean value (★☆☆)`hint: mean`
x = np.random.random(30)
print(x)
import statistics as stats
y=stats.mean(x)
print(y)



[0.52762153 0.04821976 0.68366698 0.95641942 0.18843972 0.14695172
 0.14797788 0.07462478 0.49018657 0.50265731 0.67645306 0.16346632
 0.68251081 0.34430832 0.03645059 0.14758477 0.52757596 0.72849925
 0.40416358 0.63564637 0.41194287 0.99269696 0.52844169 0.84236562
 0.96002584 0.67263287 0.0357244  0.7069354  0.38877065 0.56116639]
0.47380424652750586


In [29]:
11. # 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

x = np.diag([1, 2, 3, 4, 5])
print(x)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [31]:
12 #Normalize a 5x5 random matrix (★☆☆)

x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.16393615 0.5626105  0.82917878 0.54941643 0.14996689]
 [0.49161436 0.54314733 0.21299791 0.36076152 0.7060667 ]
 [0.1781798  0.04301468 0.84508154 0.93297441 0.88842106]
 [0.256445   0.34269005 0.11453824 0.30213082 0.99054359]
 [0.13123841 0.08982555 0.4751009  0.09895684 0.2228511 ]]
After normalization:
[[0.12761771 0.54836936 0.82969933 0.53444465 0.11287488]
 [0.47344169 0.52782838 0.17939636 0.33534264 0.6997697 ]
 [0.14265013 0.         0.84648274 0.93924282 0.89222226]
 [0.2252494  0.31627043 0.07548431 0.27346516 1.        ]
 [0.09310928 0.04940311 0.45601376 0.05904006 0.18979519]]


# 13. How to find common values between two arrays?
In NumPy, we can find common values between two arrays with the help intersect1d(). It will take parameter two arrays and it will return an array in which all the common elements will appear.

In [32]:
#14. Create a random vector of size 10 and sort it 

x = np.random.random(10)
print("Original array:", x)

x.sort()
print("Sorted array:", x)



Original array: [0.89449118 0.31916465 0.23072424 0.70724615 0.15966179 0.55043993
 0.05234961 0.56695108 0.68278263 0.56806945]
Sorted array: [0.05234961 0.15966179 0.23072424 0.31916465 0.55043993 0.56695108
 0.56806945 0.68278263 0.70724615 0.89449118]


In [36]:
#15. Create random vector of size 10 and replace the maximum value by 0 `hint: argmax`

x = np.random.random(10)

np.argmax(x)
print(x)




[0.04658805 0.49222348 0.89388894 0.72924292 0.9025562  0.26935906
 0.60882251 0.21214386 0.36723152 0.34404958]


In [37]:
#16  Subtract the mean of each row of a matrix `hint: mean(axis=,keepdims=)`

print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)

print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

#The keepdims parameter of NumPy mean enables you to control the dimensions of the output. 
#Specifically, it enables you to make the dimensions of the output 
#exactly the same as the dimensions of the input array.

Original matrix:

[[0.21419175 0.65172565 0.85623896 0.47199654 0.44550361 0.96226832
  0.26973031 0.20901024 0.88147355 0.4329518 ]
 [0.58036202 0.04856643 0.31602711 0.19347964 0.86309686 0.45453391
  0.52390957 0.42821076 0.8403086  0.61374684]
 [0.63526255 0.64137622 0.89938885 0.68729325 0.28888081 0.59346334
  0.96698074 0.13488445 0.72152248 0.292773  ]
 [0.95951877 0.17986723 0.57530734 0.46846434 0.77715038 0.09762074
  0.06063006 0.46879795 0.6955569  0.72242343]
 [0.27712855 0.62429211 0.39339901 0.69975144 0.10429814 0.11740004
  0.02621896 0.32996674 0.99505481 0.07927035]]

Subtract the mean of each row of the said matrix:

[[-0.32531732  0.11221657  0.31672988 -0.06751253 -0.09400546  0.42275924
  -0.26977876 -0.33049883  0.34196448 -0.10655727]
 [ 0.09413785 -0.43765774 -0.17019706 -0.29274453  0.37687269 -0.03169027
   0.03768539 -0.05801342  0.35408443  0.12752266]
 [ 0.04907998  0.05519365  0.31320628  0.10111068 -0.29730176  0.00728077
   0.38079817 -0.45129812  0.1

In [40]:
#17  How to get the n largest values of an array 
#`
#hint: np.argsort | np.argpartition`

n = 5

Z = np.arange(10000)   
np.random.shuffle(Z)

create numpy 1d-array


  
# sort an array in
# ascending order
  
# np.argsort() return
# array of indices for
# sorted array
sorted_index_array = np.argsort(arr)
  
# sorted array
sorted_array = arr[sorted_index_array]
  
print("Sorted array:", sorted_array)
  
# we want 5th largest value
n = 5
  
# we are using negative
# indexing concept
  
# find n largest value
rslt = sorted_array[-n : ]
  
# show the output
print("{} largest value:".format(n),
      rslt)



SyntaxError: invalid syntax (3510768321.py, line 10)